#!/usr/bin/env python3
"""
Protected Spin^c V4 two-center ramification-flux lock gate.

This optional diagnostic checks the discrete algebraic-topology step after V3:

  V3: C = CP^1, conditional on no-hidden-moduli projective minimality.
  V4: two faithful unit centers lock R = p_+ + p_- and L_R = O(R) = O(2).

The check is deliberately conservative.  It records that the lock is not a
consequence of the index count alone; it needs the parent-side input that each
projected center carries exactly one unit of source/ramification/flux and that
both centers are faithful.

Outputs:
  - output/spinc_bridge/spinc_ramification_flux_lock_summary.csv
  - output/spinc_bridge/spinc_ramification_flux_lock_detail.csv
  - output/spinc_bridge/spinc_ramification_flux_lock_detail.json
"""

from __future__ import annotations

import argparse
import csv
import json
from fractions import Fraction
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTDIR = ROOT / "output" / "spinc_bridge"


def cp1_h0_o(n: int) -> int:
    return max(n + 1, 0)


def cp1_h1_o(n: int) -> int:
    return max(-n - 1, 0)


def plummer_unit_charge() -> Fraction:
    """Exact normalized Plummer charge.

    For rho_eps(r)=3 eps^2/[4 pi (r^2+eps^2)^(5/2)],

      int_R3 rho_eps d^3x
      = int_0^infty 3 eps^2 r^2/(r^2+eps^2)^(5/2) dr
      = int_0^infty 3 t^2/(1+t^2)^(5/2) dt
      = [t^3/(1+t^2)^(3/2)]_0^infty
      = 1.

    The exact result is independent of eps.
    """
    return Fraction(1, 1)


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    ap = argparse.ArgumentParser(description="Check V4 two-center ramification-flux lock.")
    ap.add_argument("--max-multiplicity", type=int, default=4)
    ap.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    args = ap.parse_args()

    if args.max_multiplicity < 2:
        raise SystemExit("--max-multiplicity must be at least 2")

    q_plus = plummer_unit_charge()
    q_minus = plummer_unit_charge()
    unit_source_pass = q_plus == 1 and q_minus == 1

    # Enumerate effective divisors supported on the two marked centers.
    divisor_rows: list[dict[str, Any]] = []
    for m_plus in range(args.max_multiplicity + 1):
        for m_minus in range(args.max_multiplicity + 1):
            degree = m_plus + m_minus
            faithful_two_center = m_plus >= 1 and m_minus >= 1
            unit_two_center = m_plus == 1 and m_minus == 1
            minimal_faithful = faithful_two_center and degree == 2
            line_bundle = f"O({degree})"
            h0 = cp1_h0_o(degree)
            h1 = cp1_h1_o(degree)
            divisor_rows.append(
                {
                    "m_plus": m_plus,
                    "m_minus": m_minus,
                    "degree": degree,
                    "faithful_two_center": faithful_two_center,
                    "unit_two_center": unit_two_center,
                    "minimal_faithful": minimal_faithful,
                    "line_bundle_class_on_CP1": line_bundle,
                    "h0": h0,
                    "h1": h1,
                    "index": h0 - h1,
                    "interpretation": (
                        "selected R=p_+ + p_-"
                        if unit_two_center
                        else (
                            "faithful but higher ramification; rejected by unit/minimality"
                            if faithful_two_center
                            else "not faithful to both centers"
                        )
                    ),
                }
            )

    faithful = [row for row in divisor_rows if row["faithful_two_center"]]
    minimal = [row for row in faithful if row["minimal_faithful"]]
    selected = [row for row in divisor_rows if row["unit_two_center"]]

    minimal_unique_pass = len(minimal) == 1 and minimal[0]["m_plus"] == 1 and minimal[0]["m_minus"] == 1
    selected_pass = len(selected) == 1 and selected[0]["degree"] == 2

    degree_r = 2
    pic_cp1_rank = 1
    pic_class = "Z generated by O(1)"
    line_bundle = f"O({degree_r})"
    h0 = cp1_h0_o(degree_r)
    h1 = cp1_h1_o(degree_r)
    index = h0 - h1

    one_center_h0 = cp1_h0_o(1)
    one_center_index = one_center_h0 - cp1_h1_o(1)
    double_center_degree = 3
    double_center_h0 = cp1_h0_o(double_center_degree)
    double_center_index = double_center_h0 - cp1_h1_o(double_center_degree)

    v4_pass = (
        unit_source_pass
        and minimal_unique_pass
        and selected_pass
        and pic_cp1_rank == 1
        and line_bundle == "O(2)"
        and h0 == 3
        and h1 == 0
        and index == 3
        and one_center_index == 2
        and double_center_index == 4
    )
    status = (
        "CONDITIONAL_O2_LOCKED_BY_UNIT_TWO_CENTER_FLUX"
        if v4_pass
        else "V4_RAMIFICATION_FLUX_LOCK_CHECK_FAILED"
    )

    summary_rows = [
        {
            "check": "unit_source_charge_per_center",
            "value": f"q_plus={q_plus}; q_minus={q_minus}",
            "target": "each projected center carries unit charge/ramification",
            "pass": unit_source_pass,
            "status": "exact_Plummer_normalization",
        },
        {
            "check": "minimal_faithful_two_center_divisor",
            "value": f"minimal={(minimal[0]['m_plus'], minimal[0]['m_minus']) if minimal else None}",
            "target": "unique minimal faithful multiplicities are (1,1)",
            "pass": minimal_unique_pass,
            "status": "integer_effective_divisor",
        },
        {
            "check": "ramification_divisor_degree",
            "value": "R = p_+ + p_-; deg R = 2",
            "target": "degree two divisor supported on both centers",
            "pass": selected_pass,
            "status": "conditional_on_unit_two_center_flux",
        },
        {
            "check": "pic_cp1_degree_lock",
            "value": f"Pic(CP1)={pic_class}; L_R={line_bundle}",
            "target": "O(R) is determined by deg R=2, hence O(2)",
            "pass": pic_cp1_rank == 1 and line_bundle == "O(2)",
            "status": "exact_CP1_Picard",
        },
        {
            "check": "o2_dolbeault_count",
            "value": f"h0={h0}; h1={h1}; index={index}",
            "target": "h0=3; h1=0; index=3",
            "pass": h0 == 3 and h1 == 0 and index == 3,
            "status": "exact",
        },
        {
            "check": "non_unit_no_go",
            "value": f"one_center_index={one_center_index}; degree3_index={double_center_index}",
            "target": "omitting a center gives 2, higher ramification gives >3",
            "pass": one_center_index == 2 and double_center_index == 4,
            "status": "no_go",
        },
        {
            "check": "v4_ramification_flux_status",
            "value": status,
            "target": "do not read as unconditional unless unit two-center flux is derived from parent",
            "pass": v4_pass,
            "status": status,
        },
    ]

    detail = {
        "scope": "optional Spin^c V4 ramification-flux lock; no baseline scan change",
        "inputs": {
            "curve": "CP^1 from V3 conditional projective minimality",
            "centers": ["p_+", "p_-"],
            "unit_source_charge_per_center": str(q_plus),
            "faithfulness": "both centers must appear in the effective divisor",
            "minimality": "no higher local ramification multiplicity unless a new parent datum is opened",
        },
        "theorem": (
            "Under faithful unit two-center flux, the effective ramification divisor is "
            "R=p_+ + p_-. Since Pic(CP^1)=Z generated by O(1), O(R) has degree two "
            "and is isomorphic to O(2)."
        ),
        "no_go": (
            "The two-center support alone permits m_+ p_+ + m_- p_-; omitting a center "
            "is not faithful and higher multiplicities are extra ramification data. "
            "Thus O(2) is locked only after unit/minimal multiplicity is imposed or "
            "derived from the parent source normalization."
        ),
        "summary_status": status,
        "selected_divisor": {"m_plus": 1, "m_minus": 1, "degree": 2, "line_bundle": "O(2)"},
        "comparison": {
            "single_center_degree_one_index": one_center_index,
            "degree_three_higher_ramification_index": double_center_index,
        },
        "divisor_table": divisor_rows,
    }

    out_summary = args.outdir / "spinc_ramification_flux_lock_summary.csv"
    out_detail_csv = args.outdir / "spinc_ramification_flux_lock_detail.csv"
    out_detail_json = args.outdir / "spinc_ramification_flux_lock_detail.json"

    write_csv(out_summary, summary_rows, ["check", "value", "target", "pass", "status"])
    write_csv(
        out_detail_csv,
        divisor_rows,
        [
            "m_plus",
            "m_minus",
            "degree",
            "faithful_two_center",
            "unit_two_center",
            "minimal_faithful",
            "line_bundle_class_on_CP1",
            "h0",
            "h1",
            "index",
            "interpretation",
        ],
    )
    out_detail_json.write_text(json.dumps(detail, indent=2) + "\n")

    print(f"[done] wrote {out_summary}")
    print(f"[done] wrote {out_detail_csv}")
    print(f"[done] wrote {out_detail_json}")
    print(f"[status] {status}")

    if not v4_pass:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
